import json
import subprocess

from argparse import ArgumentParser
from pathlib import Path
from shlex import split

from natsort import natsorted

class JSONWithCommentsDecoder(json.JSONDecoder):

    def __init__(self, **kw):
        super().__init__(**kw)

    def decode(self, s: str):
        s = '\n'.join(l for l in s.split('\n')
                      if not l.lstrip(' ').startswith('//'))
        return super().decode(s)


def main():

    parser = ArgumentParser(description='Description of your program')
    parser.add_argument('-f','--path', help='Data folder generated by MOMA', required=True, default=Path.cwd() / Path("data"))
    args = parser.parse_args()

    BASE_PATH = args.path
    CONFIG_PATH = "include/config_current.json"

    with open("include/config.json", "r") as file:
        configuration = json.load(file, cls=JSONWithCommentsDecoder)
    print(configuration)

    for path in natsorted((BASE_PATH / Path("paths")).iterdir()):

        configuration["scenario"]["waypoints"] = (path / "path.json").as_posix()
        configuration["scenario"]["terrain"] = {}
        configuration["scenario"]["terrain"]["path"] = (
            BASE_PATH / Path("map/map-elevation-0.bmp")).as_posix()
        configuration["scenario"]["terrain"]["meta"] = (
            BASE_PATH / Path("map/map-meta-0.json")).as_posix()
        configuration["scenario"]["terrain"]["texture"] = (
            BASE_PATH / Path("map/map-diffuse-0.png")).as_posix()
        configuration["output"] = {}
        configuration["output"]["filename"] = (path / "results").as_posix()

        with open("include/config_current.json", "w") as file:
            json.dump(configuration, file)
            print(configuration)
        subprocess.run(split(f'dyno --scenario terrainMobility --options {CONFIG_PATH}'))

        break

if __name__ == '__main__':
    main()
