services:
  dyno:
    command: /usr/local/bin/dyno --scenario sideslopeStability --configuration /home/robot/workspace/options.json
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              device_ids: [ nvidia.com/gpu=all ]
    environment:
      - DISPLAY=${DISPLAY}
    image: aarhus-robotics/dyno
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      - ./options.json:/home/robot/workspace/options.json
      - /tmp/.X11-unix:/tmp/.X11-unix
