/*
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 +                            _     _     _     _                            +
 +                           / \   / \   / \   / \                           +
 +                          ( D ) ( Y ) ( N ) ( O )                          +
 +                           \_/   \_/   \_/   \_/                           +
 +                                                                           +
 +              DYNO: Ground Vehicle Dynamics Validation Toolkit             +
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

MIT License

Copyright (c) 2024 Dario Sirangelo

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <limits>
#include <random>

#include <dyno/exceptions/exceptions.hpp>

namespace DYNO {
namespace Math {

/**
 * @brief A class to generate samples using the Poisson disk sampling
 * algoirhtm.
 *
 * This class provides functionality to generate a set of samples
 * distributed according to the Poisson disk sampling algorithm. The
 * algorithm ensures that no two points are closer than a specified minimum
 * distance.
 *
 * This is a virtual class, and its derived classes may provide an
 * implementation of the Poisson disk sampling algorithm for different
 * dimension or with different constraints.
 */
class PoissonDiskSampler {
   public:
    /**
     * @brief Construct a new Poisson disk sampler.
     *
     * @param minimum_distance The minimum distance between two neighbor
     * samples.
     */
    PoissonDiskSampler(double minimum_distance);

    /**
     * @brief Generate a new batch of samples filling the entire disk.
     */
    void Generate();

    /**
     * @brief Generate a new batch of samples with size between the lower and
     * upper bounds specified.
     *
     * @param lower_bound The lower bound for the samples batch size.
     * @param upper_bound The upper bound for the samples batch size.
     */
    void Generate(unsigned int lower_bound, unsigned int upper_bound);

    /**
     * @brief Generate a new batch of samples of the specified size.
     *
     * @param number_of_samples The number of samples to be generated in this
     * batch.
     */
    virtual void Generate(unsigned int number_of_samples) = 0;

    /**
     * @brief Seed the random number generator (RNG) with an auto-generated
     * seed.
     */
    void Seed();

    /**
     * @brief Seed the random number generator (RNG) with the specified seed.
     *
     * @param seed The seed to be fed to the random number generator.
     */
    void Seed(unsigned int seed);

    /**
     * @brief Set the minimum distance between two neighbor samples.
     *
     * @remark Note that this distance should not include the radius of the
     * samples, which is accounted for automatically.
     *
     * @param distance The minimum distance between two neighbor samples.
     */
    void SetMinimumDistance(double distance);

    /**
     * @brief Set the bounds for the radii of the generated samples.
     *
     * Radii are generated by sampling a uniform distribution within the bounds
     * defined through this method.
     *
     * @param radius_min The minimum radius for a generated sample.
     * @param radius_max The maximum radius for a generated sample.
     */
    void SetRadiusRange(double radius_min, double radius_max);

    /**
     * @brief Set the number of iterations.
     *
     * This method sets the number of iteraions performed when sampling in then
     * neighborhood of a candidate point before a new sample is drawn.
     *
     * @param iterations The number of iterations to be performed.
     */
    void SetIterations(unsigned int iterations);

   protected:
    /**
     * @brief Generate a new random floating point double precision number in
     * the bounds-inclusive range [0.0, 1.0] sampled for a uniform distribution.
     *
     * @return double The generated double precision number.
     */
    double GenerateRandomNumber();

    /**
     * @brief Initialize the grid over which the samples are drawn.
     *
     * This function computes the required grid cell size for the algorithm and
     * (re-)initializes the grid over which samples are drawn. There may only be
     * at most one sample in each cell of the grid.
     *
     * This is a virtual method, and derived classes should provide their own
     * specilization of this method to account for different dimensionality or
     * grid cell size computations.
     *
     */
    virtual void InitializeGrid() = 0;

    /** @brief The minimum distance between two neighbor samples. */
    double minimum_distance_;

    /** @brief Indicates whether the sampler has already computed a valid batch
     * of samples that may be retrieved. */
    bool has_result_ = false;

    /** @brief The minimum radius for a generated sample. */
    double radius_min_ = 0.0;

    /** @brief The maximum radius for a generated sample. */
    double radius_max_ = 0.0;

    /**
     * @brief Generate a new radius for a sample.
     *
     * This function samples a uniform distribution to generated a sample radius
     * within the specified bounds.
     *
     * @return double The generated sample radius.
     */
    double GenerateSampleRadius();

    /** @brief The number of iterations performed when sampling in the
     * neighborhood of a candidate point before a new sample is drawn. */
    unsigned int iterations_ = 25;

   private:
    /** @brief A non-deterministic integer random number generator used to seed
     * the PRNG. */
    std::random_device random_device_;

    /** @brief A Mersenne-Twister pseudo-random number generator. */
    std::mt19937 random_engine_;

    /** @brief A uniform distribution used when sampling double precision
     * numbers. */
    std::uniform_real_distribution<double> uniform_distribution_;

    /**
     * @brief Initialize the pseudo-random number generator (PRNG) and the
     * uniform distribution from which the samples are drawn.
     *
     */
    void InitializePRNG();
};

}  // namespace Math
}  // namespace DYNO
