networks:
  ros:
    name: ros
    external: true

services:
  dyno:
    container_name: dyno_devcontainer_ros
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              device_ids: [ nvidia.com/gpu=all ]
    environment:
      - DISPLAY=${DISPLAY}
    image: ghcr.io/au-agv/dyno:ros-devel
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      - ../../:/home/robot/workspace
      # (Optional) Explicit ROS workspace mount
      #- ../../ros:/home/robot/ROS/src/au-agv
      - /tmp/.X11-unix:/tmp/.X11-unix
